import time
from selenium import webdriver
driver = webdriver.Firefox()
driver.get("https://twitter.com/")
time.sleep(3)
link = driver.find_element_by_xpath("/html/body/div/div/div/div/main/div/div/div/div[1]/div/div[3]/a[2]")
time.sleep(3)
link.click()
time.sleep(3)
campo_User= driver.find_element_by_xpath("/html/body/div/div/div/div[2]/main/div/div/div[2]/form/div/div[1]/label/div/div[2]/div/input")
time.sleep(3)
campo_User.send_keys('nombreUsuarioTweeter')
time.sleep(3)
campo_Password= driver.find_element_by_xpath("/html/body/div/div/div/div[2]/main/div/div/div[2]/form/div/div[2]/label/div/div[2]/div/input")
time.sleep(3)
campo_Password.send_keys('contraseñaUsuarioTweeter')
time.sleep(3)
bt_Login = driver.find_element_by_xpath("/html/body/div/div/div/div[2]/main/div/div/div[2]/form/div/div[3]/div")
time.sleep(3)
bt_Login.click()
time.sleep(3)
campo_Trino = driver.find_element_by_xpath('//div[@class="notranslate public-DraftEditor-content" and @role="textbox"]')
time.sleep(3)
campo_Trino.send_keys('Este trino tambien es hecho por un bot programado en el curso Specialist @dsteamseguridad ;-)')
time.sleep(3)
bt_Tweet = driver.find_element_by_xpath("/html/body/div/div/div/div[2]/main/div/div/div/div[1]/div/div[2]/div/div[2]/div[1]/div/div/div/div[2]/div[4]/div/div/div[2]/div[3]/div/span/span")
time.sleep(3)
bt_Tweet.click()
